version: '3'
name: rabbitmq-management
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    # environment:
      # RABBITMQ_DEFAULT_USER_FILE: guest
      # RABBITMQ_DEFAULT_PASS_FILE: guest